export interface BnccMapping {
  id: string; // Habilidade principal BNCC
  gameId: string;
  faixaEtaria: '0-3' | '4-5' | '6-8' | '9-12' | '13+';
  etapaEnsino: 'Educação Infantil' | 'Ensino Fundamental I' | 'Ensino Fundamental II';
  habilidadeBncc: string;
  descricaoBncc: string;
  campoExperiencia?: string; // Para Educação Infantil
  subject?: string; // Para Ensino Fundamental
  eixoCognitivo: 'Alfabetização' | 'Raciocínio Lógico' | 'Socioemocional' | 'Percepção Sensorial' | 'Coordenação Visomotora';
  nivelDificuldade: 'Fácil' | 'Médio' | 'Difícil' | 'Adaptativo';
  tagsPedagogicas: string[];
  
  // Propriedades estendidas (Fase 5 - Matriz Pedagógica BNCC)
  level: number; // Nível associado (1, 2 ou 3)
  fase: string; // Fase lúdica
  objetivoCognitivo: string; // Objetivo cognitivo específico
  mecanica: string; // Nome legível da mecânica
  competenciasTrabalhadas: string[]; // Competências secundárias desenvolvidas
}

export const BNCC_MAPPING_DATA: BnccMapping[] = [
  // --- Bebês e Bem pequenas (0 a 3 anos) ---
  {
    id: 'EI01TS01',
    gameId: 'orquestra_sons',
    faixaEtaria: '0-3',
    etapaEnsino: 'Educação Infantil',
    habilidadeBncc: 'EI01TS01',
    descricaoBncc: 'Explorar sons produzidos com o próprio corpo e com objetos do ambiente.',
    campoExperiencia: 'Traços, sons, cores e formas',
    eixoCognitivo: 'Percepção Sensorial',
    nivelDificuldade: 'Fácil',
    tagsPedagogicas: ['Estímulo Sonoro', 'Estímulo Tátil', 'Causa e Efeito'],
    level: 1,
    fase: 'Fase 1 - Sons da Natureza',
    objetivoCognitivo: 'Causa e efeito tátil-auditiva',
    mecanica: 'Toques Musicais Suaves',
    competenciasTrabalhadas: ['Atenção primária', 'Exploração sonora']
  },
  {
    id: 'EI01TS03',
    gameId: 'orquestra_sons',
    faixaEtaria: '0-3',
    etapaEnsino: 'Educação Infantil',
    habilidadeBncc: 'EI01TS03',
    descricaoBncc: 'Explorar diferentes fontes sonoras e materiais para acompanhar ritmos musicais.',
    campoExperiencia: 'Traços, sons, cores e formas',
    eixoCognitivo: 'Percepção Sensorial',
    nivelDificuldade: 'Fácil',
    tagsPedagogicas: ['Musicalização', 'Atenção Auditiva', 'Calmante'],
    level: 2,
    fase: 'Fase 2 - Instrumentos Musicais',
    objetivoCognitivo: 'Diferenciação e escuta ativa de fontes sonoras',
    mecanica: 'Tons de Calmaria',
    competenciasTrabalhadas: ['Foco auditivo', 'Regulação emocional']
  },
  {
    id: 'EI01CG05',
    gameId: 'toque_cores',
    faixaEtaria: '0-3',
    etapaEnsino: 'Educação Infantil',
    habilidadeBncc: 'EI01CG05',
    descricaoBncc: 'Utilizar os movimentos de preensão, encaixe e lançamento, ampliando suas possibilidades de manuseio de diferentes materiais.',
    campoExperiencia: 'Corpo, gestos e movimentos',
    eixoCognitivo: 'Coordenação Visomotora',
    nivelDificuldade: 'Fácil',
    tagsPedagogicas: ['Precisão de Toque', 'Visomotor', 'Calmante'],
    level: 2,
    fase: 'Fase 2 - Harmonia Cromática',
    objetivoCognitivo: 'Reforçar coordenação óculo-manual de toque',
    mecanica: 'Pareamento de Cores Pastéis',
    competenciasTrabalhadas: ['Coordenação motora fina', 'Precisão espacial']
  },
  {
    id: 'EI01TS02',
    gameId: 'toque_cores',
    faixaEtaria: '0-3',
    etapaEnsino: 'Educação Infantil',
    habilidadeBncc: 'EI01TS02',
    descricaoBncc: 'Traçar marcas gráficas sobre diferentes superfícies, utilizando elements visuais (ponto, linha, forma e cor).',
    campoExperiencia: 'Traços, sons, cores e formas',
    eixoCognitivo: 'Percepção Sensorial',
    nivelDificuldade: 'Fácil',
    tagsPedagogicas: ['Rastreamento Visual', 'Cromoterapia', 'Regulação Sensorial'],
    level: 1,
    fase: 'Fase 1 - Toques Mágicos',
    objetivoCognitivo: 'Interação e rastreamento cromático reativo',
    mecanica: 'Ecos de Luz e Causa-Efeito',
    competenciasTrabalhadas: ['Rastreamento ocular', 'Foco visual']
  },
  {
    id: 'EI02ET05',
    gameId: 'balao_formas',
    faixaEtaria: '0-3',
    etapaEnsino: 'Educação Infantil',
    habilidadeBncc: 'EI02ET05',
    descricaoBncc: 'Classificar objetos, considerando determinado atributo (tamanho, peso, cor, forma etc.).',
    campoExperiencia: 'Espaços, tempos, quantidades, relações e transformações',
    eixoCognitivo: 'Raciocínio Lógico',
    nivelDificuldade: 'Adaptativo',
    tagsPedagogicas: ['Diferenciação de Formas', 'Pareamento Visual', 'Geometria Espacial'],
    level: 1,
    fase: 'Fase 1 - Formas e Balões',
    objetivoCognitivo: 'Diferenciar e parear figuras planas primárias',
    mecanica: 'Atenção Seletiva e Cliques',
    competenciasTrabalhadas: ['Reconhecimento geométrico', 'Seleção visual']
  },
  {
    id: 'EI02ET01',
    gameId: 'balao_formas',
    faixaEtaria: '0-3',
    etapaEnsino: 'Educação Infantil',
    habilidadeBncc: 'EI02ET01',
    descricaoBncc: 'Compartilhar com outras crianças a exploração de espaços e de objetos com diferentes características.',
    campoExperiencia: 'Espaços, tempos, quantidades, relações e transformações',
    eixoCognitivo: 'Raciocínio Lógico',
    nivelDificuldade: 'Adaptativo',
    tagsPedagogicas: ['Atenção Sustentada', 'Exploração Ativa', 'Coordenação Fina'],
    level: 2,
    fase: 'Fase 2 - Trilha de Padrões',
    objetivoCognitivo: 'Compreensão de repetição lógica sequencial',
    mecanica: 'Sequência Lógica',
    competenciasTrabalhadas: ['Raciocínio indutivo', 'Atenção focalizada']
  },
  {
    id: 'EI02EO01',
    gameId: 'termometro_sentimentos_infantil',
    faixaEtaria: '0-3',
    etapaEnsino: 'Educação Infantil',
    habilidadeBncc: 'EI02EO01',
    descricaoBncc: 'Demonstrar atitudes de cuidado e solidariedade na interação com crianças e adultos.',
    campoExperiencia: 'O eu, o outro e o nós',
    eixoCognitivo: 'Socioemocional',
    nivelDificuldade: 'Médio',
    tagsPedagogicas: ['Empatia', 'Autocuidado', 'Inteligência Emocional'],
    level: 2,
    fase: 'Fase 2 - Expressando Emoções',
    objetivoCognitivo: 'Reconhecer sentimentos em situações comuns',
    mecanica: 'Interpretação Emocional',
    competenciasTrabalhadas: ['Vocabulário socioafetivo', 'Empatia guiada']
  },
  {
    id: 'EI02EO04',
    gameId: 'termometro_sentimentos_infantil',
    faixaEtaria: '0-3',
    etapaEnsino: 'Educação Infantil',
    habilidadeBncc: 'EI02EO04',
    descricaoBncc: 'Comunicar-se com colegas e adultos, buscando ajuda e expressando sentimentos, necessidades e opiniões.',
    campoExperiencia: 'O eu, o outro e o nós',
    eixoCognitivo: 'Socioemocional',
    nivelDificuldade: 'Médio',
    tagsPedagogicas: ['Reconhecimento Facial', 'Comunicação Afetiva', 'Autoexpressão'],
    level: 1,
    fase: 'Fase 1 - Galeria das Carinhas',
    objetivoCognitivo: 'Identificação visual de rostos e expressões',
    mecanica: 'Reconhecimento Facial',
    competenciasTrabalhadas: ['Expressão facial', 'Autoreconhecimento']
  },

  // --- Crianças pequenas - Pré-Escola (4 a 5 anos) ---
  {
    id: 'EI03EO01',
    gameId: 'termometro_sentimentos',
    faixaEtaria: '4-5',
    etapaEnsino: 'Educação Infantil',
    habilidadeBncc: 'EI03EO01',
    descricaoBncc: 'Demonstrar empatia pelos outros, percebendo que as pessoas têm diferentes sentimentos, necessidades e maneiras de pensar e agir.',
    campoExperiencia: 'O eu, o outro e o nós',
    eixoCognitivo: 'Socioemocional',
    nivelDificuldade: 'Adaptativo',
    tagsPedagogicas: ['Empatia', 'Perspectiva Social', 'Regulação Emocional'],
    level: 2,
    fase: 'Fase 2 - Empatia e Reações',
    objetivoCognitivo: 'Avaliar a reação do colega diante de sentimentos',
    mecanica: 'Interpretação Emocional',
    competenciasTrabalhadas: ['Empatia ativa', 'Percepção social']
  },
  {
    id: 'EI03EO02',
    gameId: 'termometro_sentimentos',
    faixaEtaria: '4-5',
    etapaEnsino: 'Educação Infantil',
    habilidadeBncc: 'EI03EO02',
    descricaoBncc: 'Agir de maneira independente, com confiança em suas capacidades, reconhecendo suas conquistas e limitações.',
    campoExperiencia: 'O eu, o outro e o nós',
    eixoCognitivo: 'Socioemocional',
    nivelDificuldade: 'Adaptativo',
    tagsPedagogicas: ['Autoestima', 'Resiliência', 'Tomada de Decisão'],
    level: 3,
    fase: 'Fase 3 - Convivência Cooperativa',
    objetivoCognitivo: 'Compreensão ética e cooperação autônoma',
    mecanica: 'Escolhas de Empatia Guiada',
    competenciasTrabalhadas: ['Autonomia ética', 'Resolução de conflitos']
  },
  {
    id: 'EI03EF09',
    gameId: 'cacadores_letras_infantil',
    faixaEtaria: '4-5',
    etapaEnsino: 'Educação Infantil',
    habilidadeBncc: 'EI03EF09',
    descricaoBncc: 'Recorrer a estratégias diversas para pautar a escrita espontânea, mostrando interesse em escrever palavras e textos.',
    campoExperiencia: 'Escuta, fala, pensamento e imaginação',
    eixoCognitivo: 'Alfabetização',
    nivelDificuldade: 'Adaptativo',
    tagsPedagogicas: ['Alfabetização Inicial', 'Escrita Espontânea', 'Fonemas'],
    level: 1,
    fase: 'Fase 1 - Vogal e Som',
    objetivoCognitivo: 'Associação grafofônica inicial em figuras',
    mecanica: 'Caça Letras',
    competenciasTrabalhadas: ['Letramento visual', 'Fonética primária']
  },
  {
    id: 'EI03EF03',
    gameId: 'cacadores_letras_infantil',
    faixaEtaria: '4-5',
    etapaEnsino: 'Educação Infantil',
    habilidadeBncc: 'EI03EF03',
    descricaoBncc: 'Escolher e folhear livros, mostrando preferência por gêneros, temas e ilustrações, e identificando seus autores.',
    campoExperiencia: 'Escuta, fala, pensamento e imaginação',
    eixoCognitivo: 'Alfabetização',
    nivelDificuldade: 'Adaptativo',
    tagsPedagogicas: ['Consciência Fonológica', 'Vocabulário', 'Foco Atento'],
    level: 2,
    fase: 'Fase 2 - Pedaços de Palavras',
    objetivoCognitivo: 'Identificar a sílaba tônica inicial de imagens',
    mecanica: 'Montar Sílabas',
    competenciasTrabalhadas: ['Aliteração', 'Atenção auditiva']
  },

  // --- Ensino Fundamental I - Alfabetização (6 a 8 anos) ---
  {
    id: 'EF15LP18',
    gameId: 'cacadores_letras',
    faixaEtaria: '6-8',
    etapaEnsino: 'Ensino Fundamental I',
    habilidadeBncc: 'EF15LP18',
    descricaoBncc: 'Relacionar elementos sonoros (sílabas, fonemas, partes de palavras) com sua representação escrita.',
    subject: 'Língua Portuguesa',
    eixoCognitivo: 'Alfabetização',
    nivelDificuldade: 'Adaptativo',
    tagsPedagogicas: ['Ortografia', 'Consciência Silábica', 'Grafofônica'],
    level: 2,
    fase: 'Fase 2 - Sílaba Faltante',
    objetivoCognitivo: 'Parear a sílaba escrita exata na lacuna',
    mecanica: 'Montar Sílabas',
    competenciasTrabalhadas: ['Ortografia silábica', 'Consciência grafofonêmica']
  },
  {
    id: 'EF01LP08',
    gameId: 'cacadores_letras',
    faixaEtaria: '6-8',
    etapaEnsino: 'Ensino Fundamental I',
    habilidadeBncc: 'EF01LP08',
    descricaoBncc: 'Relacionar elementos sonoros de palavras com sua representação escrita.',
    subject: 'Língua Portuguesa',
    eixoCognitivo: 'Alfabetização',
    nivelDificuldade: 'Adaptativo',
    tagsPedagogicas: ['Leitura Autônoma', 'Associação Grafema-Fonema', 'Segmentação'],
    level: 1,
    fase: 'Fase 1 - Grafema e Letra',
    objetivoCognitivo: 'Completar letras faltantes na palavra',
    mecanica: 'Caça Letras',
    competenciasTrabalhadas: ['Ortografia básica', 'Leitura fonética']
  },
  {
    id: 'EF15AR02',
    gameId: 'quebra_cabeca_formas',
    faixaEtaria: '6-8',
    etapaEnsino: 'Ensino Fundamental I',
    habilidadeBncc: 'EF15AR02',
    descricaoBncc: 'Explorar e reconhecer elementos constitutivos das artes visuais (ponto, linha, forma, cor, espaço, movimento etc.).',
    subject: 'Artes',
    eixoCognitivo: 'Raciocínio Lógico',
    nivelDificuldade: 'Adaptativo',
    tagsPedagogicas: ['Tangram', 'Rotação Mental', 'Simetria'],
    level: 3,
    fase: 'Fase 3 - Memória e Arte das Formas',
    objetivoCognitivo: 'Memorização e ordenação visual espacial',
    mecanica: 'Memória Visual',
    competenciasTrabalhadas: ['Memória de trabalho', 'Visoespacial']
  },
  {
    id: 'EF01MA14',
    gameId: 'quebra_cabeca_formas',
    faixaEtaria: '6-8',
    etapaEnsino: 'Ensino Fundamental I',
    habilidadeBncc: 'EF01MA14',
    descricaoBncc: 'Identificar e nomear figuras geométricas planas (círculo, quadrado, retângulo e triângulo) em desenhos e objetos.',
    subject: 'Matemática',
    eixoCognitivo: 'Raciocínio Lógico',
    nivelDificuldade: 'Adaptativo',
    tagsPedagogicas: ['Geometria Plana', 'Resolução de Problemas', 'Foco'],
    level: 1,
    fase: 'Fase 1 - Moldes Planos',
    objetivoCognitivo: 'Identificar figuras planas no tangram abstrato',
    mecanica: 'Atenção Seletiva',
    competenciasTrabalhadas: ['Figuras geométricas planas', 'Análise de atributos']
  },
  {
    id: 'EF01MA01',
    gameId: 'reino_numeros',
    faixaEtaria: '6-8',
    etapaEnsino: 'Ensino Fundamental I',
    habilidadeBncc: 'EF01MA01',
    descricaoBncc: 'Utilizar números naturais como indicadores de quantidade ou de ordem em diferentes situações cotidianas.',
    subject: 'Matemática',
    eixoCognitivo: 'Raciocínio Lógico',
    nivelDificuldade: 'Médio',
    tagsPedagogicas: ['Contagem Ativa', 'Conceito Numérico', 'Correspondência'],
    level: 1,
    fase: 'Fase 1 - Contando Elementos',
    objetivoCognitivo: 'Parear quantidade de figuras ao numeral escrito',
    mecanica: 'Contar Objetos',
    competenciasTrabalhadas: ['Princípio da contagem', 'Cardinalidade']
  },
  {
    id: 'EF01MA04',
    gameId: 'reino_numeros',
    faixaEtaria: '6-8',
    etapaEnsino: 'Ensino Fundamental I',
    habilidadeBncc: 'EF01MA04',
    descricaoBncc: 'Contar a quantidade de objetos de coleções de até 20 elements e apresentar o resultado por registros verbais e simbólicos.',
    subject: 'Matemática',
    eixoCognitivo: 'Raciocínio Lógico',
    nivelDificuldade: 'Médio',
    tagsPedagogicas: ['Adição Básica', 'Associação de Grupos', 'Subtração Ilustrada'],
    level: 3,
    fase: 'Fase 3 - Somas da Fazenda',
    objetivoCognitivo: 'Adição básica simplificada com apoio pictórico',
    mecanica: 'Mini Desafios Matemáticos',
    competenciasTrabalhadas: ['Operações aritméticas básicas', 'Soma visual']
  },

  // --- Ensino Fundamental I - Intermediários (9 a 12 anos) ---
  {
    id: 'EF06MA09',
    gameId: 'desafio_sequencias',
    faixaEtaria: '9-12',
    etapaEnsino: 'Ensino Fundamental II',
    habilidadeBncc: 'EF06MA09',
    descricaoBncc: 'Resolver e elaborar problemas que envolvam números fracionários ou sequências recursivas estruturadas.',
    subject: 'Matemática',
    eixoCognitivo: 'Raciocínio Lógico',
    nivelDificuldade: 'Difícil',
    tagsPedagogicas: ['Lógica Algorítmica', 'Pensamento Sequencial', 'Decomposição'],
    level: 1,
    fase: 'Fase 1 - Atenção a Comandos',
    objetivoCognitivo: 'Atenção seletiva a fluxos lógicos computacionais',
    mecanica: 'Atenção Seletiva',
    competenciasTrabalhadas: ['Pensamento computacional', 'Sequenciação']
  },
  {
    id: 'EF08MA11',
    gameId: 'desafio_sequencias',
    faixaEtaria: '9-12',
    etapaEnsino: 'Ensino Fundamental II',
    habilidadeBncc: 'EF08MA11',
    descricaoBncc: 'Identificar e criar expressões que descrevam regularidades em sequências de figuras ou padrões numéricos.',
    subject: 'Matemática',
    eixoCognitivo: 'Raciocínio Lógico',
    nivelDificuldade: 'Difícil',
    tagsPedagogicas: ['Reconhecimento de Padrões', 'Estruturas de Decisão', 'Tangível'],
    level: 2,
    fase: 'Fase 2 - Trilha de Algoritmos',
    objetivoCognitivo: 'Completar padrões estruturados e laços',
    mecanica: 'Sequência Lógica',
    competenciasTrabalhadas: ['Reconhecimento de padrões', 'Abstração lógica']
  },

  // --- Ensino Fundamental II - Anos Finais (13+ anos) ---
  {
    id: 'EF06ER07',
    gameId: 'detetive_social',
    faixaEtaria: '13+',
    etapaEnsino: 'Ensino Fundamental II',
    habilidadeBncc: 'EF06ER07',
    descricaoBncc: 'Avaliar e exercitar caminhos éticos para a convivência social em comunidades pluralistas e inclusivas.',
    subject: 'Ensino Religioso / Socioemocional',
    eixoCognitivo: 'Socioemocional',
    nivelDificuldade: 'Adaptativo',
    tagsPedagogicas: ['Ética', 'Cidadania', 'Inclusão Social'],
    level: 1,
    fase: 'Fase 1 - Expressão Social',
    objetivoCognitivo: 'Percepção facial de sentimentos em situações sociais',
    mecanica: 'Reconhecimento Facial',
    competenciasTrabalhadas: ['Percepção de sentimentos', 'Socialização']
  },
  {
    id: 'EF08ER04',
    gameId: 'detetive_social',
    faixaEtaria: '13+',
    etapaEnsino: 'Ensino Fundamental II',
    habilidadeBncc: 'EF08ER04',
    descricaoBncc: 'Debater sobre a diversidade cultural e o respeito às diferenças individuais como base democrática.',
    subject: 'Ensino Religioso / Socioemocional',
    eixoCognitivo: 'Socioemocional',
    nivelDificuldade: 'Adaptativo',
    tagsPedagogicas: ['Respeito à Diversidade', 'Pensamento Crítico', 'Cooperação'],
    level: 2,
    fase: 'Fase 2 - Mediação e Empatia',
    objetivoCognitivo: 'Avaliação de sentimentos de outrem em discussões escolares',
    mecanica: 'Interpretação Emocional',
    competenciasTrabalhadas: ['Pensamento crítico', 'Mediação de dilemas']
  },
  // --- NOVOS MAPEAMENTOS ADICIONADOS ---
  {
    id: 'EI03EF01',
    gameId: 'caca_letras_4_6',
    faixaEtaria: '4-5',
    etapaEnsino: 'Educação Infantil',
    habilidadeBncc: 'EI03EF01',
    descricaoBncc: 'Expressar ideias, desejos e sentimentos sobre suas vivências, por meio da linguagem oral e escrita (escrita espontânea), de fotos, desenhos e outras formas de expressão.',
    campoExperiencia: 'Escuta, fala, pensamento e imaginação',
    eixoCognitivo: 'Alfabetização',
    nivelDificuldade: 'Fácil',
    tagsPedagogicas: ['Linguagem', 'Grafemas', 'Reconhecimento Letras'],
    level: 1,
    fase: 'Fase 1 - Descobrindo Letras',
    objetivoCognitivo: 'Reconhecimento de grafemas básicos',
    mecanica: 'Caça Letras',
    competenciasTrabalhadas: ['Foco atento', 'Letramento']
  },
  {
    id: 'EI03MA01',
    gameId: 'formas_cores_4_6',
    faixaEtaria: '4-5',
    etapaEnsino: 'Educação Infantil',
    habilidadeBncc: 'EI03MA01',
    descricaoBncc: 'Registrar observações, manipulações e medidas, usando múltiplas linguagens (desenho, registro por números ou escrita espontânea), em diferentes suportes.',
    campoExperiencia: 'Espaços, tempos, quantidades, relações e transformações',
    eixoCognitivo: 'Coordenação Visomotora',
    nivelDificuldade: 'Fácil',
    tagsPedagogicas: ['Formas Geométricas', 'Coordenação', 'Visomotor'],
    level: 1,
    fase: 'Fase 1 - Formas Básicas',
    objetivoCognitivo: 'Reconhecimento e pareamento de figuras',
    mecanica: 'Cores Sensoriais',
    competenciasTrabalhadas: ['Precisão visomotora', 'Classificação geométrica']
  },
  {
    id: 'EF01MA06',
    gameId: 'somando_brincando_7_9',
    faixaEtaria: '6-8',
    etapaEnsino: 'Ensino Fundamental I',
    habilidadeBncc: 'EF01MA06',
    descricaoBncc: 'Construir fatos básicos da adição e utilizá-los em procedimentos de cálculo para resolver problemas.',
    subject: 'Matemática',
    eixoCognitivo: 'Raciocínio Lógico',
    nivelDificuldade: 'Médio',
    tagsPedagogicas: ['Adição Básica', 'Cálculo Mental', 'Lógica'],
    level: 1,
    fase: 'Fase 1 - Somas Divertidas',
    objetivoCognitivo: 'Fatos básicos de adição simples',
    mecanica: 'Contar Objetos',
    competenciasTrabalhadas: ['Contagem cardinal', 'Soma aritmética']
  },
  {
    id: 'EF02LP09',
    gameId: 'historia_interativa_7_9',
    faixaEtaria: '6-8',
    etapaEnsino: 'Ensino Fundamental I',
    habilidadeBncc: 'EF02LP09',
    descricaoBncc: 'Ler e compreender, com autonomia, textos curtos, com estrutura narrativa simples, considerando a fidedignidade da leitura.',
    subject: 'Língua Portuguesa',
    eixoCognitivo: 'Alfabetização',
    nivelDificuldade: 'Médio',
    tagsPedagogicas: ['Interpretação Textual', 'Narrativa', 'Compreensão Leitora'],
    level: 1,
    fase: 'Fase 1 - O Pequeno Explorador',
    objetivoCognitivo: 'Interpretação de textos curtos elementares',
    mecanica: 'Completar Frases',
    competenciasTrabalhadas: ['Leitura autônoma', 'Associação semântica']
  },
  {
    id: 'EF05MA07',
    gameId: 'desafio_fracoes_10_12',
    faixaEtaria: '9-12',
    etapaEnsino: 'Ensino Fundamental I',
    habilidadeBncc: 'EF05MA07',
    descricaoBncc: 'Resolver e elaborar problemas de adição e subtração com números fracionários, utilizando representações pictóricas ou equivalência.',
    subject: 'Matemática',
    eixoCognitivo: 'Raciocínio Lógico',
    nivelDificuldade: 'Difícil',
    tagsPedagogicas: ['Frações Equivalentes', 'Visualização Espacial', 'Matemática'],
    level: 1,
    fase: 'Fase 1 - Fatias Equivalentes',
    objetivoCognitivo: 'Identificar frações equivalentes com figuras de pizza',
    mecanica: 'Mini Desafios',
    competenciasTrabalhadas: ['Fração de um todo', 'Lógica matemática avançada']
  },
  {
    id: 'EF04GE03',
    gameId: 'mapa_regioes_10_12',
    faixaEtaria: '9-12',
    etapaEnsino: 'Ensino Fundamental I',
    habilidadeBncc: 'EF04GE03',
    descricaoBncc: 'Diferenciar territórios, identificando as grandes regiões do Brasil.',
    subject: 'Geografia',
    eixoCognitivo: 'Coordenação Visomotora',
    nivelDificuldade: 'Difícil',
    tagsPedagogicas: ['Regiões do Brasil', 'Espacial', 'Localização Geográfica'],
    level: 1,
    fase: 'Fase 1 - Descobrindo o Brasil',
    objetivoCognitivo: 'Raciocínio espacial e localização de estados/regiões',
    mecanica: 'Atenção Seletiva',
    competenciasTrabalhadas: ['Geografia política', 'Análise de mapas']
  },
  {
    id: 'EI01TS01',
    gameId: 'musicalizacao_infantil_0_3',
    faixaEtaria: '0-3',
    etapaEnsino: 'Educação Infantil',
    habilidadeBncc: 'EI01TS01',
    descricaoBncc: 'Explorar sons produzidos com o próprio corpo e com objetos do ambiente.',
    campoExperiencia: 'Traços, sons, cores e formas',
    eixoCognitivo: 'Percepção Sensorial',
    nivelDificuldade: 'Fácil',
    tagsPedagogicas: ['Atenção Auditiva', 'Causa e Efeito', 'Musicalização'],
    level: 1,
    fase: 'Fase 1 - Sons e Timbres',
    objetivoCognitivo: 'Identificar sons e timbres básicos',
    mecanica: 'Causa e Efeito Sonora',
    competenciasTrabalhadas: ['Discriminação auditiva', 'Escuta ativa']
  },
  {
    id: 'EI01TS02',
    gameId: 'musicalizacao_infantil_0_3',
    faixaEtaria: '0-3',
    etapaEnsino: 'Educação Infantil',
    habilidadeBncc: 'EI01TS02',
    descricaoBncc: 'Traçar marcas gráficas sobre diferentes superfícies, utilizando elementos visuais (ponto, linha, forma e cor).',
    campoExperiencia: 'Traços, sons, cores e formas',
    eixoCognitivo: 'Percepção Sensorial',
    nivelDificuldade: 'Fácil',
    tagsPedagogicas: ['Sons Naturais', 'Sons Culturais', 'Sons do Cotidiano'],
    level: 1,
    fase: 'Fase 1 - Sons e Timbres',
    objetivoCognitivo: 'Diferenciar sons naturais e criados pelo homem',
    mecanica: 'Causa e Efeito Sonora',
    competenciasTrabalhadas: ['Consciência ecológica sonora', 'Classificação de sons']
  },
  {
    id: 'EI01CG01',
    gameId: 'musicalizacao_infantil_0_3',
    faixaEtaria: '0-3',
    etapaEnsino: 'Educação Infantil',
    habilidadeBncc: 'EI01CG01',
    descricaoBncc: 'Movimentar as partes do corpo para exprimir corporalmente emoções, necessidades e sentimentos.',
    campoExperiencia: 'Corpo, gestos e movimentos',
    eixoCognitivo: 'Coordenação Visomotora',
    nivelDificuldade: 'Médio',
    tagsPedagogicas: ['Ritmo Rápido', 'Ritmo Lento', 'Movimento Corporal'],
    level: 3,
    fase: 'Fase 3 - Ritmo e Notas',
    objetivoCognitivo: 'Expressão corporal integrada ao pulso musical',
    mecanica: 'Coordenação Motora',
    competenciasTrabalhadas: ['Ritmo corporal', 'Autoconhecimento motor']
  },
  {
    id: 'EI01EF01',
    gameId: 'musicalizacao_infantil_0_3',
    faixaEtaria: '0-3',
    etapaEnsino: 'Educação Infantil',
    habilidadeBncc: 'EI01EF01',
    descricaoBncc: 'Reconhecer quando é chamado por seu nome e responder a ordens simples.',
    campoExperiencia: 'Escuta, fala, pensamento e imaginação',
    eixoCognitivo: 'Percepção Sensorial',
    nivelDificuldade: 'Médio',
    tagsPedagogicas: ['Duração do Som', 'Altura do Som', 'Intensidade'],
    level: 2,
    fase: 'Fase 2 - Propriedades do Som',
    objetivoCognitivo: 'Diferenciar duração, intensidade e altura de sons',
    mecanica: 'Cores Sensoriais',
    competenciasTrabalhadas: ['Atenção sustentada', 'Diferenciação acústica']
  }
];

